### ISSUE TITLE
Don't include Dashicons by default

### ISSUE THREAD

**Issue by krafit** [schlessera/as-speaking#4]
as-speaking is not loading Dashicons. So while viewing the talks page as a not logged-in user they won't show up (see attached screenshot).

I'd suggest to remove them from the plugin entirely. 
Icons are kind of theme territory and will probably be changed in many use-cases anyway.

![bildschirmfoto 2017-10-11 um 21 13 39](https://user-images.githubusercontent.com/1038789/31461290-630574bc-aec9-11e7-948d-f3482753abc4.png)

**Comment by schlessera** [comment]
Ah, yes, that's an issue. I had added these because the plugin was meant to be a demonstration, and I had trouble coming up with a usable base display.

I will look into this.

**Comment by schlessera** [comment]
@krafit Dashicons are gone now. However, I wanted to add _some_ styling still, as the point was to demonstrate enqueueing a CSS stylesheet while rendering a shortcode.

Here's the new default output on my site:
![image 2017-10-28 at 5 54 47 pm](https://user-images.githubusercontent.com/83631/32136068-44bd604e-bc09-11e7-8cca-739f5cb15900.png)

**Comment by schlessera** [comment]
@krafit Also, in case you already had done some custom styling, be aware that I changed the class names, to have a BEM-like notation.

**Comment by krafit** [comment]
<3
